### ISSUE TITLE
Issue while running the make in examples folder in pathmarks-scripts

### ISSUE THREAD

**Issue by akhtar4ever** [sng87/paradigmshift#2]
Hi,

have been trying to use the tool paradigm-shift,  downloaded the required dependency :pathmark-scripts and and ran make in the base folder.
Post which I sourced init.sh file and when I am running make in examples folder I am getting error.

Below is the sequence of command execution:

[aktar@centos pathmark-scripts]$ make
[aktar@centos pathmark-scripts]$ source  init.sh
[aktar@centos pathmark-scripts]$ cd  examples/
[aktar@centos examples]$ make
galaxyPATHMARK.py -z 123454321 -n 10 -b 10 -f "1.0;1.0" data/merge_merged.all.tab data/feature.tab data/pid_500_pathway.tab
/home/aktar/paradigm-shift/pathmark-scripts/bin/signature.py:10: FutureWarning: The pandas.rpy module is deprecated and will be removed in a future version. We refer to external packages like rpy2.
See here for a guide on how to port your code to rpy2: http://pandas.pydata.org/pandas-docs/stable/r_interface.html
  import pandas.rpy.common as common
WARNING: '.jobTree' directory found, remove it first to start a fresh run

options: {'maxThreads': 4, 'rescueJobsFrequency': None, 'logLevel': 'CRITICAL', 'jobTime': 30, 'logRotating': False, 'logOff': False, 'logDebug': False, 'null_permute': 'paradigm', 'stats': False, 'maxJobs': 9223372036854775807, 'defaultCpu': 1, 'signature_method': 'sam', 'jobFile': None, 'reportAllJobLogFiles': False, 'logInfo': False, 'bootstrap_size': '10', 'parasolCommand': 'parasol', 'null_size': '10', 'maxLogFileSize': 50120, 'defaultMemory': 2147483648, 'jobTree': None, 'seed': '123454321', 'command': None, 'maxJobDuration': '9223372036854775807', 'batchSystem': 'singleMachine', 'retryCount': 0, 'logFile': None}
Using Batch System 'singleMachine'
Job: /home/aktar/paradigm-shift/pathmark-scripts/examples/.jobTree/jobs/tmp_VNea92Q5Ck/tmp_s8pyXedHj9/tmp_Dt6XrS4fr4.xml failed
The log file of the job
Reporting file: /home/aktar/paradigm-shift/pathmark-scripts/examples/.jobTree/logFileDir/tmp_YNJj6whnez/tmp_eNaOnHwERT/tmp_RUgdewzsVe.log
tmp_RUgdewzsVe.log:     Traceback (most recent call last):
tmp_RUgdewzsVe.log:       File "/home/aktar/paradigm-shift/paradigm-scripts/jobTree/bin/jobTreeSlave", line 116, in processJob
tmp_RUgdewzsVe.log:         jobTree.scriptTree.scriptTree.run(tempJob, l[1], l[2:])
tmp_RUgdewzsVe.log:       File "/home/aktar/paradigm-shift/paradigm-scripts/jobTree/scriptTree/scriptTree.py", line 44, in run
tmp_RUgdewzsVe.log:         target.execute(job)
tmp_RUgdewzsVe.log:       File "/home/aktar/paradigm-shift/paradigm-scripts/jobTree/scriptTree/stack.py", line 150, in execute
tmp_RUgdewzsVe.log:         self.target.run()
tmp_RUgdewzsVe.log:       File "/home/aktar/paradigm-shift/pathmark-scripts/bin/PATHMARK.py", line 1041, in run
tmp_RUgdewzsVe.log:         real_graph = readNetworkXSIF("analysis/%s/%s" % (signature, real_file), node_type_map = self.global_pathway.nodes)
tmp_RUgdewzsVe.log:       File "/home/aktar/paradigm-shift/pathmark-scripts/bin/PATHMARK.py", line 692, in readNetworkXSIF
tmp_RUgdewzsVe.log:         f = open(input_file, "r")
tmp_RUgdewzsVe.log:     IOError: [Errno 2] No such file or directory: 'analysis/Basal.vs.Luminal=+_SIGNATURE/Basal.vs.Luminal=+_SIGNATURE_1.0_1.0.sif'
The log file of the slave for the job
Reporting file: /home/aktar/paradigm-shift/pathmark-scripts/examples/.jobTree/slaveLogFileDir/tmp_w67l6ACQAE/tmp_jZcPaeH8sb/tmp_Fpq3q3N8bf.log
tmp_Fpq3q3N8bf.log:     Caught an exception in the target being run
tmp_Fpq3q3N8bf.log:     Failed the job
tmp_Fpq3q3N8bf.log:     Exiting the slave because of a failed job
Job: /home/aktar/paradigm-shift/pathmark-scripts/examples/.jobTree/jobs/tmp_VNea92Q5Ck/tmp_s8pyXedHj9/tmp_Dt6XrS4fr4.xml is completely failed
WARNING: 1 jobs failed
Using Batch System 'singleMachine'
Job: /home/aktar/paradigm-shift/pathmark-scripts/examples/.jobTree/jobs/tmp_VNea92Q5Ck/tmp_s8pyXedHj9/tmp_Dt6XrS4fr4.xml failed
The log file of the job
Reporting file: /home/aktar/paradigm-shift/pathmark-scripts/examples/.jobTree/logFileDir/tmp_YNJj6whnez/tmp_eNaOnHwERT/tmp_RUgdewzsVe.log
tmp_RUgdewzsVe.log:     Traceback (most recent call last):
tmp_RUgdewzsVe.log:       File "/home/aktar/paradigm-shift/paradigm-scripts/jobTree/bin/jobTreeSlave", line 116, in processJob
tmp_RUgdewzsVe.log:         jobTree.scriptTree.scriptTree.run(tempJob, l[1], l[2:])
tmp_RUgdewzsVe.log:       File "/home/aktar/paradigm-shift/paradigm-scripts/jobTree/scriptTree/scriptTree.py", line 44, in run
tmp_RUgdewzsVe.log:         target.execute(job)
tmp_RUgdewzsVe.log:       File "/home/aktar/paradigm-shift/paradigm-scripts/jobTree/scriptTree/stack.py", line 150, in execute
tmp_RUgdewzsVe.log:         self.target.run()
tmp_RUgdewzsVe.log:       File "/home/aktar/paradigm-shift/pathmark-scripts/bin/PATHMARK.py", line 1041, in run
tmp_RUgdewzsVe.log:         real_graph = readNetworkXSIF("analysis/%s/%s" % (signature, real_file), node_type_map = self.global_pathway.nodes)
tmp_RUgdewzsVe.log:       File "/home/aktar/paradigm-shift/pathmark-scripts/bin/PATHMARK.py", line 692, in readNetworkXSIF
tmp_RUgdewzsVe.log:         f = open(input_file, "r")
tmp_RUgdewzsVe.log:     IOError: [Errno 2] No such file or directory: 'analysis/Basal.vs.Luminal=+_SIGNATURE/Basal.vs.Luminal=+_SIGNATURE_1.0_1.0.sif'
The log file of the slave for the job
Reporting file: /home/aktar/paradigm-shift/pathmark-scripts/examples/.jobTree/slaveLogFileDir/tmp_w67l6ACQAE/tmp_jZcPaeH8sb/tmp_Fpq3q3N8bf.log
tmp_Fpq3q3N8bf.log:     Caught an exception in the target being run
tmp_Fpq3q3N8bf.log:     Failed the job
tmp_Fpq3q3N8bf.log:     Exiting the slave because of a failed job
Job: /home/aktar/paradigm-shift/pathmark-scripts/examples/.jobTree/jobs/tmp_VNea92Q5Ck/tmp_s8pyXedHj9/tmp_Dt6XrS4fr4.xml is completely failed

Contents of examples folder
[aktar@centos examples]$ ls -l
total 1916
drwxrwxr-x 4 aktar aktar   4096 Mar 28 17:14 analysis
-rw-rw-r-- 1 aktar aktar 862170 Mar 28 17:14 bootstrap_signature.tab
drwxrwxr-x 2 aktar aktar   4096 Feb 20  2015 data
-rw-rw-r-- 1 aktar aktar   2553 Apr  4 19:21 galaxy-pathmark.log
drwxrwxr-x 2 aktar aktar   4096 Mar 28 17:06 img
-rw-rw-r-- 1 aktar aktar    431 Feb 20  2015 Makefile
-rw-rw-r-- 1 aktar aktar 887184 Mar 28 17:14 null_signature.tab
-rw-rw-r-- 1 aktar aktar   1517 Apr  4 19:21 signature.log
-rw-rw-r-- 1 aktar aktar 182837 Mar 28 17:14 signature.tab
[aktar@centos examples]$ cd ..

Contents of pathmark-scripts
[aktar@centos pathmark-scripts]$ ls -l
total 32
drwxrwxr-x 2 aktar aktar 4096 Mar 28 17:14 bin
drwxrwxr-x 4 aktar aktar 4096 Feb 20  2015 cytoscape
drwxrwxr-x 7 aktar aktar 4096 Mar 28 17:14 examples
-rw-rw-r-- 1 aktar aktar  252 Mar 28 17:05 init.csh
-rw-rw-r-- 1 aktar aktar  416 Mar 28 17:13 init.sh
-rw-rw-r-- 1 aktar aktar 1125 Feb 20  2015 Makefile
lrwxrwxrwx 1 aktar aktar   65 Mar 28 17:05 paradigm-scripts -> /home/aktar/paradigm-shift/pathmark-scripts/../paradigm-scripts
-rw-rw-r-- 1 aktar aktar 3012 Feb 20  2015 README.md
[aktar@centos pathmark-scripts]$

Your guidance is required to use the tool.
I would highly obliged for your assistance, looking forward for your reply

**Comment by akhtar4ever** [comment]
Hi,

I am trying tousethis tool, code is exiting abruptly :
tmp_IxHJ2nupjP.log:       File "/home/cwtools/ps/paradigm-scripts/jobTree/bin/jobTreeSlave", line 119, in processJob
tmp_IxHJ2nupjP.log:         jobTree.scriptTree.scriptTree.run(tempJob, l[1], l[2:])
tmp_IxHJ2nupjP.log:       File "/home/cwtools/ps/paradigm-scripts/jobTree/scriptTree/scriptTree.py", line 45, in run
tmp_IxHJ2nupjP.log:         target.execute(job)
tmp_IxHJ2nupjP.log:       File "/home/cwtools/ps/paradigm-scripts/jobTree/scriptTree/stack.py", line 151, in execute
tmp_IxHJ2nupjP.log:         self.target.run()
tmp_IxHJ2nupjP.log:       File "/home/cwtools/ps/pathmark-scripts/bin/PATHMARK.py", line 986, in run
tmp_IxHJ2nupjP.log:         signature_graph = getPathmark(score_frame,global_graph,self.parameters,forced_statistics = score_statistics)
tmp_IxHJ2nupjP.log:       File "/home/cwtools/ps/pathmark-scripts/bin/PATHMARK.py", line 552, in getPathmark
tmp_IxHJ2nupjP.log:         if node in global_graph.edges:
tmp_IxHJ2nupjP.log:       File "/usr/lib/python2.7/site-packages/networkx/classes/reportviews.py", line 1100, in __contains__
tmp_IxHJ2nupjP.log:         raise ValueError("MultiEdge must have length 2 or 3")
tmp_IxHJ2nupjP.log:     ValueError: MultiEdge must have length 2 or 3
The log file of the slave for the job
Reporting file: /home/cwtools/ps/pathmark-scripts/examples/.jobTree/slaveLogFileDir/tmp_vuq4J1jb4o/tmp_MrNJOsuWGd/tmp_fR75iamepC.log
tmp_fR75iamepC.log:     Caught an exception in the target being run
tmp_fR75iamepC.log:     Failed the job
tmp_fR75iamepC.log:     Exiting the slave because of a failed job
Job: /home/cwtools/ps/pathmark-scripts/examples/.jobTree/jobs/tmp_1HcAPrld8r/tmp_NBsaq1cNwu/tmp_xl7ER2sitZ.xml is completely failed


Would request you to give me suggestion on proceeding with this tool.

It will be really a great help and I would be highly obliged.

Thanks
Aktar
